<?php

/**
 * @file
 * Contains switch_sharerich.module.
 */

/**
 * Implements hook_switch_info().
 */
function switch_sharerich_switch_info() {
  return array(
    'disable_sharerich' => array(
      'label' => 'Disable Sharerich',
      'entity_types' => array('node'),
    ),
  );
}

/**
 * Implements hook_sharerich_set_load_alter().
 *
 * @param $set
 */
function switch_sharerich_sharerich_set_load_alter(&$set) {
  if (path_is_admin(current_path())) {
    return;
  }

  $node = menu_get_object('node', 1);
  if (node_is_page($node)) {
    if (switch_is_enabled('node', $node->nid, 'disable_sharerich')) {
      $set->disabled = TRUE;
    }
  }
}
